version: '3'

vars:
  MODULE_PATH: 'github.com/7cout/minissp'

tasks:

  default:
    desc: "Показать список доступных задач"
    cmds:
      - task --list

  format:
    desc: "Форматирует весь проект gofumpt + gci"
    cmds:
      - go tool gofumpt -extra -w .
      - go tool gci write -s standard -s default -s "prefix({{.MODULE_PATH}})" .

  lint:
    desc: "Запускает golangci-lint для всех модулей"
    cmds:
      - go tool golangci-lint run ./... --config=.golangci.yml

  test:
    desc: "Запустить тесты с детектором гонок"
    cmds:
      - go test -race -count=1 ./...

  all:
    desc: "Полный цикл проверок: fmt - lint - test"
    cmds:
      - task: format
      - task: lint
      - task: test